[package]
authors = ["kononnable <kononnable@gmail.com>"]
edition = "2018"
name = "toy-payments-engine"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
thiserror = "1.0.24"
